---
stages:
  - test
  - release
  - build

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
.kaniko_template_defaults:
  stage: build
include:
  - { project: fsrvcorp/templates, file: templates/language/go.yml, ref: 1.0.5 }
  - { project: fsrvcorp/templates, file: templates/release/semver.yml, ref: 1.0.5 }
  - { project: fsrvcorp/templates, file: templates/release/kaniko.yml, ref: 1.0.5 }

Integration Tests:
  image: ubuntu-22.04
  stage: test
  needs:
    - go fmt
  tags:
    - hcloud
  variables:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  before_script:
    - (apt update && apt install -y curl git) > /dev/null 2>&1
    - curl -sSL https://go.dev/dl/go1.21.5.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - /usr/local/go/bin/go install gotest.tools/gotestsum@latest
  script:
    - bash -x integration-tests/setup.sh
    - eval $(cat .env)
    - /usr/local/go/bin/go test -v ./integration-tests/... --tags integration -json | /root/go/bin/gotestsum --junitfile report.xml --format testname --raw-command -- cat
  artifacts:
    reports:
      junit: report.xml
    when: always
