---
version: '3'
services:
  postgres-1:
    image: postgres:16@sha256:ff37e66b0a03594086c3734d73e750f13480ca9bf64b53fafea18be4d5afb9ad
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
