---
version: '3'
services:
  postgres-1:
    image: postgres:16
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
