apiVersion: fsrv.cloud/v1
kind: Database
metadata:
  name: demo
spec:
  database: postgres
---
apiVersion: fsrv.cloud/v1
kind: Database
metadata:
  name: demo2
spec:
  database: postgres
---
apiVersion: fsrv.cloud/v1
kind: Database
metadata:
  name: demo3
spec:
  database: postgres
