apiVersion: v1
kind: ServiceAccount
metadata:
  name:  external-db-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-db-operator-role
rules:
  - apiGroups: ["bonsai-oss.org"]
    resources: ["databases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-db-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: external-db-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-db-operator-role
  apiGroup: rbac.authorization.k8s.io
