---
apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: bonsai-oss.org/v1
kind: Database
metadata:
  name: demo
  namespace: foo
  labels:
    bonsai-oss.org/external-db-operator: postgres-default
