---
version: '3'
services:
  postgres-1:
    image: postgres:16@sha256:3fc654768ae8431e28fa326ca2998b374bb0acea7904ba4894938bf470d8ed50
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
